# Importing Required Libraries

In [1]:
import pandas as pd

DATA_PATH = r'D:\Data_Analyst_Project\Online_Retail_Business_Analysis\01_Data\Raw_Data'

# Importing Raw Data

In [2]:
order_item_refunds = pd.read_csv(rf'{DATA_PATH}\order_item_refunds.csv')
order_items = pd.read_csv(rf'{DATA_PATH}\order_items.csv')
orders = pd.read_csv(rf'{DATA_PATH}\orders.csv')
products = pd.read_csv(rf'{DATA_PATH}\products.csv')
website_pageviews = pd.read_csv(rf'{DATA_PATH}\website_pageviews.csv')
website_sessions = pd.read_csv(rf'{DATA_PATH}\website_sessions.csv')

# Profiling Orders

In [3]:
orders.head()

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

In [4]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

In [5]:
orders.describe()

,order_id,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
count,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000
mean,16157.000000,258292.288707,215691.622629,1.392474,1.238666,59.991636,22.355406
std,9328.103961,132427.649842,108402.203189,0.732277,0.426274,17.808771,6.238621
min,1.000000,20.000000,13.000000,1.000000,1.000000,29.990000,9.490000
25%,8079.000000,144828.000000,124135.000000,1.000000,1.000000,49.990000,19.490000
50%,16157.000000,263554.000000,221461.000000,1.000000,1.000000,49.990000,19.490000
75%,24235.000000,374799.000000,310542.000000,2.000000,1.000000,59.990000,22.490000
max,32313.000000,472818.000000,394273.000000,4.000000,2.000000,109.980000,41.980000

In [6]:
orders.shape

(32313, 8)

In [7]:
orders.isnull().sum()

order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

In [8]:
orders['order_id'].duplicated().sum()

np.int64(0)

In [9]:
orders['created_at'] = pd.to_datetime(orders['created_at'])
orders['created_at'].min(), orders['created_at'].max()

(Timestamp('2012-03-19 10:42:46'), Timestamp('2015-03-19 05:38:31'))

### Profiling Summary for Orders
| Check | Observation |
|-------|-------------|
| Grain | 1 row is a single order |
| Rows | 32313 |
| Columns | 8 |
| Missing Values | 0 |
| Duplicate Order IDs | 0 |
| Date Range | 19/03/2012 to 19/03/2015 |
| Price Range | $29.9 to $109.9 |
| COGS Range | $9.4 to $41.9 |
| Distribution Observation | price_usd appears positively/right-skewed, as the mean is higher than the median. This should be confirmed through distribution analysis. |

# Profiling Order Items

In [10]:
order_items.head()

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

In [11]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  object
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 2.1+ MB

In [12]:
order_items.describe()

,order_item_id,order_id,product_id,is_primary_item,price_usd,cogs_usd
count,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000
mean,20013.000000,17121.957502,1.770019,0.807320,48.432473,18.047976
std,11554.366599,9053.765867,1.085561,0.394408,8.012370,3.856821
min,1.000000,1.000000,1.000000,0.000000,29.990000,9.490000
25%,10007.000000,9871.000000,1.000000,1.000000,49.990000,19.490000
50%,20013.000000,17490.000000,1.000000,1.000000,49.990000,19.490000
75%,30019.000000,24818.000000,2.000000,1.000000,49.990000,19.490000
max,40025.000000,32313.000000,4.000000,1.000000,59.990000,22.490000

In [13]:
order_items.isnull().sum()

order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

In [14]:
order_items['order_item_id'].duplicated().sum()

np.int64(0)

In [15]:
order_items['order_id'].duplicated().sum()

np.int64(7712)

In [16]:
order_items['created_at'] = pd.to_datetime(order_items['created_at'])
order_items['created_at'].min(), order_items['created_at'].max()

(Timestamp('2012-03-19 10:42:46'), Timestamp('2015-03-19 05:38:31'))

In [17]:
order_items.groupby('order_id').size().describe()

count    32313.000000
mean         1.238666
std          0.426274
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
dtype: float64

### Profiling Summary for Orders Items
| Check | Observation |
|-------|-------------|
| Grain | 1 row represents one order item (product line) within an order |
| Rows | 40025 |
| Columns | 7 |
| Missing Values | 0 |
| Duplicate Order Item IDs | 0 |
| Repeated Order ID Rows | 7712 |
| Date Range | 19/03/2012 to 19/03/2015 |
| Price Range | $29.9 to $59.9 |
| COGS Range | $9.4 to $22.9 |
| Distribution Observation | nothing notable |
| Items per Order | Average 1.24; median 1; maximum 2 |
| Order Composition | ~76.1% of orders contain 1 item; ~23.9% contain 2 items |

**Analytical Note:** order_items has a lower grain than orders. An order can contain multiple order-item rows, which explains the repeated order_id values. Therefore, order-level metrics should not be summed after directly joining to order_items without accounting for the one-to-many relationship.

# Profiling Order Item Refunds

In [18]:
order_item_refunds.head()

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99

In [19]:
order_item_refunds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   object
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 67.7+ KB

In [20]:
order_item_refunds.describe()

       order_item_refund_id  order_item_id      order_id  refund_amount_usd
count           1731.000000    1731.000000   1731.000000        1731.000000
mean             866.000000   18472.214905  15868.242057          49.300225
std              499.840975   11438.074606   9096.061945           4.956015
min                1.000000      57.000000     57.000000          29.990000
25%              433.500000    7417.000000   7412.000000          49.990000
50%              866.000000   19858.000000  17375.000000          49.990000
75%             1298.500000   26900.000000  22539.500000          49.990000
max             1731.000000   39950.000000  32255.000000          59.990000

In [21]:
order_item_refunds.isnull().sum()

order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

In [22]:
order_item_refunds['order_item_refund_id'].duplicated().sum()

np.int64(0)

In [23]:
order_item_refunds['order_item_id'].duplicated().sum()

np.int64(0)

In [24]:
order_item_refunds['order_id'].duplicated().sum()

np.int64(8)

In [25]:
order_item_refunds.groupby('order_id').size().describe()

count    1723.000000
mean        1.004643
std         0.068001
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
dtype: float64

In [26]:
order_item_refunds['created_at'] = pd.to_datetime(order_item_refunds['created_at'])
order_item_refunds['created_at'].min(), order_item_refunds['created_at'].max()

(Timestamp('2012-04-06 11:32:43'), Timestamp('2015-04-01 18:11:08'))

### Profiling Summary for Order Item Refunds
| Check | Observation |
|-------|-------------|
| Grain | 1 row represents a refund record for one order item |
| Rows | 1731 |
| Columns | 5 |
| Missing Values | 0 |
| Duplicate Order Item Refund IDs | 0 |
| Duplicate Order Item IDs | 0 |
| Repeated Order ID Rows | 8 |
| Date Range | 06/04/2012 to 01/04/2015 |
| Refund Amount Range | $29.9 to $59.9 |
| Distribution Observation | Nothing notable |

# Profiling Products

In [27]:
products

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

In [28]:
products['created_at'] = pd.to_datetime(products['created_at'])
products['created_at'].min(), products['created_at'].max()

(Timestamp('2012-03-19 08:00:00'), Timestamp('2014-02-05 10:00:00'))

### Profiling Summary for Products

| Check | Observation |
|---|---|
| Grain | 1 row represents one product |
| Rows | 4 |
| Columns | 3 |
| Missing Values | 0 |
| Product IDs | 1–4, all unique |
| Products | 4 |
| Creation Dates | 19/03/2012 to 05/02/2014 |

**Analytical Note:** `products` is a small reference table containing product attributes and creation dates. No further statistical profiling is necessary due to its very small size.

# Profiling Website Pageviews

In [29]:
website_pageviews.head()

   website_pageview_id           created_at  website_session_id pageview_url
0                    1  2012-03-19 08:04:16                   1        /home
1                    2  2012-03-19 08:16:49                   2        /home
2                    3  2012-03-19 08:26:55                   3        /home
3                    4  2012-03-19 08:37:33                   4        /home
4                    5  2012-03-19 09:00:55                   5        /home

In [30]:
website_pageviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188124 entries, 0 to 1188123
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1188124 non-null  int64
 1   created_at           1188124 non-null  object
 2   website_session_id   1188124 non-null  int64
 3   pageview_url         1188124 non-null  object
dtypes: int64(2), object(2)
memory usage: 36.3+ MB

In [31]:
website_pageviews.isnull().sum()

website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64

In [32]:
website_pageviews['website_session_id'].duplicated().sum()

np.int64(715253)

In [33]:
website_pageviews['pageview_url'].nunique()

16

In [34]:
website_pageviews.groupby('website_session_id').size().describe()

count    472871.000000
mean          2.512575
std           1.816384
min           1.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           7.000000
dtype: float64

In [35]:
website_pageviews['website_pageview_id'].duplicated().sum()

np.int64(0)

In [36]:
website_pageviews['created_at'] = pd.to_datetime(website_pageviews['created_at'])
website_pageviews['created_at'].min(), website_pageviews['created_at'].max()

(Timestamp('2012-03-19 08:04:16'), Timestamp('2015-03-19 07:59:32'))

### Profiling Summary for Website Pageviews
| Check                    | Observation                           |
| ------------------------ | ------------------------------------- |
| Grain                    | 1 row represents one website pageview |
| Rows                     | 1,188,124                             |
| Columns                  | 4                                     |
| Missing Values           | 0                                     |
| Duplicate Pageview IDs   | 0                                     |
| Repeated Session ID Rows | 715,253                               |
| Unique Page URLs         | 16                                    |
| Unique Website Sessions  | 472,871                               |
| Pageviews per Session    | Average 2.51; median 2; maximum 7     |
| Date Range               | 19/03/2012 to 19/03/2015              |

# Profiling Website Sessions

In [37]:
website_sessions.head()

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [38]:
website_sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  object
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: int64(3), object(6)
memory usage: 32.5+ MB

In [39]:
website_sessions.isnull().sum()

website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64

In [40]:
website_sessions['created_at'] = pd.to_datetime(website_sessions['created_at'])
website_sessions['created_at'].min(), website_sessions['created_at'].max()

(Timestamp('2012-03-19 08:04:16'), Timestamp('2015-03-19 07:59:08'))

In [41]:
website_sessions['website_session_id'].duplicated().sum()

np.int64(0)

In [42]:
website_sessions['user_id'].duplicated().sum()

np.int64(78553)

In [43]:
website_sessions.groupby('utm_source').size().describe()

count         3.000000
mean     129847.666667
std      163336.723003
min       10685.000000
25%       36754.000000
50%       62823.000000
75%      189429.000000
max      316035.000000
dtype: float64

In [44]:
website_sessions.groupby('utm_content').size().describe()

count         6.000000
mean      64923.833333
std      108515.175594
min        5095.000000
25%        6171.000000
50%       20621.500000
75%       49514.000000
max      282706.000000
dtype: float64

In [45]:
website_sessions.groupby('utm_campaign').size().describe()

count         4.000000
mean      97385.750000
std      161044.655491
min        5095.000000
25%        5466.250000
50%       23416.500000
75%      115336.000000
max      337615.000000
dtype: float64

In [46]:
website_sessions.groupby('device_type').size().describe()

count         2.000000
mean     236435.500000
std      128115.727936
min      145844.000000
25%      191139.750000
50%      236435.500000
75%      281731.250000
max      327027.000000
dtype: float64

### Profiling Summary for Website Sessions
| Check                         | Observation                              |
| ----------------------------- | ---------------------------------------- |
| Grain                         | 1 row represents one website session     |
| Rows                          | 472,871                                  |
| Columns                       | 9                                        |
| Missing Values                | Present in marketing and referrer fields |
| Duplicate Website Session IDs | 0                                        |
| Repeated User ID Rows         | 78,553                                   |
| Date Range                    | 19/03/2012 to 19/03/2015                 |
| UTM Source                    | 83,328 sessions have no UTM source       |
| UTM Campaign                  | 83,328 sessions have no UTM campaign     |
| UTM Content                   | 83,328 sessions have no UTM content      |
| HTTP Referrer                 | 39,917 sessions have no HTTP referrer    |
| Device Types                  | 2 — desktop and mobile                   |
| UTM Sources                   | 3 distinct sources                       |
| UTM Campaigns                 | 4 distinct campaigns                     |
| UTM Contents                  | 6 distinct contents                      |

**Analytical Note:** website_sessions is a session-level table, so repeated user_id values are expected: the same user can generate multiple website sessions.

The missing UTM fields are also meaningful rather than automatically being "bad data." They indicate 83,328 sessions without campaign-tracking information, which we will later be able to analyze as an untracked/direct traffic segment.

Similarly, http_referer has 39,917 missing values, meaning the referring source is unavailable for those sessions.